import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Encabezado */}
        <header className='w-full flex flex-row justify-between py-10 px-20 bg-sky-800 text-white font-bold'   >
          <h1 className='text-2xl'>Festividades de Nicaragua</h1>
          {/* <img src="imagen-principal.jpg" alt="Imagen representativa de festividades en Nicaragua" /> */}
          {/* Menú de Navegación */}
          <nav>
            <ul className='flex gap-8'>
              <li><Link href="index.html">Inicio</Link></li>
              <li><Link href="dias-festivos-principales.html">Nacionales</Link></li>
              <li><Link href="festividades-regionales.html">Municipales</Link></li>

            </ul>
          </nav>
        </header>
        {children}
        <footer className='w-full flex flex-col py-10 px-20 bg-sky-800 text-white relative '>
          <div className='flex flex-col self-center text-center justify-self-center'>
            <span>
              Copyright © 2023. Todos los derechos reservados
            </span>
            <span className='font-bold'>
              Festivos de Nicaragua
            </span>
          </div>
          <span className='self-end absolute bottom-10'>
            Diseñado por: <a href='' target="_blank" className='font-bold'>Luichix</a>
          </span>
        </footer>
      </body>
    </html>
  )
}
